seed: 42

input_data_path: data/train_essays_best.csv

model:
  backbone_path: microsoft/deberta-xlarge
  max_length: 512 
  tokenizer:
    use_fast: true

train_params:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 8
  epochs: 3
  warmup_pct: 0.1

optimizer:
  lr: 2.0e-5
  weight_decay: 0.01

outputs:
  model_dir: output/models/deberta_best
